export const USER_REGISTRATION_REQUEST: '@userDetails/USER_REGISTRATION_REQUEST' = '@userDetails/USER_REGISTRATION_REQUEST';
export const USER_REGISTRATION_SUCCESS: '@userDetails/USER_REGISTRATION_SUCCESS' = '@userDetails/USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_ERROR: '@userDetails/USER_REGISTRATION_ERROR' = '@userDetails/USER_REGISTRATION_ERROR';

export const USER_AUTHORIZATION_REQUEST: '@userDetails/USER_AUTHORIZATION_REQUEST' = '@userDetails/USER_AUTHORIZATION_REQUEST';
export const USER_AUTHORIZATION_SUCCESS: '@userDetails/USER_AUTHORIZATION_SUCCESS' = '@userDetails/USER_AUTHORIZATION_SUCCESS';
export const USER_AUTHORIZATION_ERROR: '@userDetails/USER_AUTHORIZATION_ERROR' = '@userDetails/USER_AUTHORIZATION_ERROR';

export const USER_UNAUTHORIZATION_REQUEST: '@userDetails/USER_UNAUTHORIZATION_REQUEST' = '@userDetails/USER_UNAUTHORIZATION_REQUEST';
export const USER_UNAUTHORIZATION_SUCCESS: '@userDetails/USER_UNAUTHORIZATION_SUCCESS' = '@userDetails/USER_UNAUTHORIZATION_SUCCESS';
export const USER_UNAUTHORIZATION_ERROR: '@userDetails/USER_UNAUTHORIZATION_ERROR' = '@userDetails/USER_UNAUTHORIZATION_ERROR';

export const UPDATE_USER_DETAILS_REQUEST: '@userDetails/UPDATE_USER_DETAILS_REQUEST' = '@userDetails/UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_SUCCESS: '@userDetails/UPDATE_USER_DETAILS_SUCCESS' = '@userDetails/UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_ERROR: '@userDetails/UPDATE_USER_DETAILS_ERROR' = '@userDetails/UPDATE_USER_DETAILS_ERROR';
