export const WS_CONNECTION_START: '@WS/CONNECTION_START' = '@WS/CONNECTION_START';
export const WS_CONNECTION_SUCCESS: '@WS/CONNECTION_SUCCESS' = '@WS/CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: '@WS/CONNECTION_ERROR' = '@WS/CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: '@WS/CONNECTION_CLOSED' = '@WS/CONNECTION_CLOSED';
export const WS_GET_DATA: '@WS/GET_DATA' = '@WS/GET_DATA';
